var express = require('express');
var router = express.Router();

const nameList = [
  {'Id': 1,'Term':'Software deployment','Description':' A professional activity where software is developed for specific business purposes, for inclusion in other devices, or as software products such as information systems, CAD systems, etc. Professional software, intended for use by someone apart from its developer, is usually developed by teams rather than individuals. It is maintained and changed throughout its life.','reference':'I. Sommerville et al., “SOFTWARE ENGINEERING Ninth Edition.” Available: https://engineering.futureuniversity.com/BOOKS%20FOR%20IT/Software-Engineering-9th-Edition-by-Ian-Sommerville.pdf'},
  {'Id': 2,'Term':'Software Operations','Description':'Software operations, also known as "operations" or "IT operations", refers to the practices and processes involved in managing and maintaining software systems and IT infrastructure in production environments. This includes a wide range of activities aimed at ensuring the reliability, efficiency and security of software applications and services','reference':'K. M. Nelson, S. Nadkarni, V. K. Narayanan, and M. Ghods, “Understanding Software Operations Support Expertise: A Revealed Causal Mapping Approach,” MIS Quarterly, vol. 24, no. 3, p. 475, Sep. 2000, doi: https://doi.org/10.2307/3250971.'},
  {'Id': 3, 'Term':"GIT",'Description':'Git is a free and open source distributed version control system designed to handle everything from small to very large projects with speed and efficiency.','reference':'Git, “Git,” Git-scm.com, 2019. https://git-scm.com/'},
  {'Id': 4, 'Term':"Continuous Integration (CI)",'Description':'Continuous Integration (CI) is a software development practice that aims to streamline the process of building, testing, and integrating code changes into a shared repository. By automating these tasks, CI allows developers to frequently and efficiently integrate their changes, often multiple times a day.','reference':'S. Hamdan and S. Alramouni, “A Quality Framework for Software Continuous Integration,” Procedia Manufacturing, vol. 3, pp. 2019–2025, 2015, doi: https://doi.org/10.1016/j.promfg.2015.07.249'},
  {'Id': 5, 'Term':"Continuous Deployment (CD)",'Description':'Continuous Deployment (CD) is an extension of Continuous Integration (CI) in the software development process. CD takes the automation further by automatically deploying code changes to production or a production-like environment after passing all the automated tests in the CI pipeline.','reference':'Kim, Gene, et al. "Accelerate: The Science of Lean Software and DevOps: Building and Scaling High Performing Technology Organizations." IT Revolution Press, 2018.'},
  {'Id': 6, 'Term':"Software Change Management",'Description':'The term Software Change Management refers to a structured and systematic approach that organizations use to plan, implement, and manage changes in a controlled manner.','reference':'A. A. Khan, S. Basri, and P. D. D. Dominic, “A propose framework for requirement Change Management in Global Software Development,” 2012 International Conference on Computer & Information Science (ICCIS), Jun. 2012, doi: https://doi.org/10.1109/iccisci.2012.6297161.'},
  {'Id': 7, 'Term':"Release Management",'Description':'The process involves the planning, development, testing, deployment, and monitoring of a software release.','reference':'A. van der Hoek, R. S. Hall, D. Heimbigner, and A. L. Wolf, “Software release management,” ACM SIGSOFT Software Engineering Notes, vol. 22, no. 6, pp. 159–175, Nov. 1997, doi: https://doi.org/10.1145/267896.267909.'},
  {'Id': 8, 'Term':"Downtime",'Description':'A downtime occurs when a piece of software is not available for users to use. It is the opposite of an uptime, which is a period during which the software is running.','reference':'D. Patterson, “A Simple Way to Estimate the Cost of Downtime,” 2002. Accessed: Jul. 23, 2023. [Online]. Available: http://roc.cs.berkeley.edu/papers/Cost_Downtime_LISA.pdf'},
  {'Id': 9, 'Term':"Monitoring and Alerting",'Description':'Monitoring and alerting are critical components of software operations and infrastructure management. A software performance monitor is employed to ensure that software systems perform well, are available, and reliable, as well as to detect and respond to any anomalies that may occur. Alerting is the process of setting up rules and thresholds based on predefined conditions or criteria in the monitored data. When these conditions are met or when anomalies are detected, the monitoring system generates alerts or notifications to notify the responsible teams about potential issues.','reference':'"The DevOps Handbook: How to Create World-Class Agility, Reliability, and Security in Technology Organizations" by Gene Kim, Patrick Debois, John Willis, and Jez Humble. This book covers various aspects of DevOps, including monitoring, alerting, and improving IT operations.'},
  {'Id': 10, 'Term':"Devops",'Description':'DevOps is a set of practices and cultural philosophies aimed at improving collaboration and communication between development teams (Dev) and IT operations teams (Ops). The goal is to break down the traditional silos between these teams and encourage a culture of shared ownership across the software development and delivery lifecycle','reference':'C. Ebert, G. Gallardo, J. Hernantes, and N. Serrano, “DevOps,” IEEE Software, vol. 33, no. 3, pp. 94–100, May 2016, doi: https://doi.org/10.1109/ms.2016.68. “(PDF) A Qualitative Study of DevOps Usage in Practice,” ResearchGate. https://www.researchgate.net/publication/316879884_A_Qualitative_Study_of_DevOps_Usage_in_Practic'},
  {'Id': 11, 'Term':"Continuous delivery",'Description':'Continuous delivery (CD) is a software engineering approach that produces software in short cycles, ensuring reliable release without manual intervention. It automates the SDLC from build to testing, promoting a rapid feedback loop between businesses and users. It forms the modern CI/CD delivery pipeline.','reference':'J. Verona, P. Swartout, and M. Duffy, Learning DevOps: Continuously Deliver Better Software. Birmingham, UK: Packt Publishing, 2016. Accessed: Aug. 06, 2023. [Online]. Available: https://eds.p.ebscohost.com/eds/detail/detail?vid=0&sid=095af693-cd41-4075-8dbd-6ffb6235c2d2%40redis&bdata=JnNpdGU9ZWRzLWxpdmUmc2NvcGU9c2l0ZQ%3d%3d#AN=1358183&db=e000xww'},
  {'Id': 12, 'Term':"Agile",'Description':'Agile is a project management and software development approach that emphasizes flexibility, collaboration, and incremental progress. It breaks projects into smaller tasks and iterations, focusing on customer collaboration, incremental development, adaptive planning, continuous integration, cross-functional teams, and self-organizing teams. Agile popularity stems from its ability to adapt to changing requirements, improve product quality, and foster customer satisfaction.','reference':'Agile Alliance, \“What is Agile Software Development?,\” Agile Alliance, Jan. 16, 2019. https://www.agilealliance.org/agile101/' },
  {'Id': 13, 'Term':"Git Branching",'Description':'Git branching is a version control system feature enabling developers to create separate development lines within a project, allowing teams to work independently without interfering with the main codebase. Key concepts include Master/Main Branch, branch creation, switching, committing changes, merging, conflict resolution, and branch management.','reference':'About - Git,” Git-scm.com, 2019. https://git-scm.com/about' },
  {'Id': 14, 'Term':"Repository ",'Description':'A repository is a data structure in version control systems that stores metadata for files and directory structures, allowing for distributed or centralized storage. Its purpose is to store files and their history of changes.','reference':'Git, “Git - About Version Control,” Git-scm.com, 2019. https://git-scm.com/book/en/v2/Getting-Started-About-Version-Control'}, 
  {'Id': 15, 'Term':"Commit ",'Description':'A Git commit records changes to a projects files and creates a new snapshot of the codebase. It is assigned a unique identifier called the commit hash or SHA-1 hash. To create a commit, follow these steps: add stage changes, create a commit with a descriptive message, repeat as needed, and view commit history. Git allows for easy reverting to previous states and synchronization of the codebase.','reference':'Git - git-commit Documentation,” git-scm.com."https://git-scm.com/docs/git-commit" '},
  {'Id': 16, 'Term':"Continuous improvement (CIP)",'Description':'Continuous improvement (CIP) is a philosophy aiming to create a culture where team members can suggest and improve products or processes at any time. It is a fundamental principle in management philosophies like Lean, Six Sigma, Total Quality Management, and Agile. By embracing CIP, organizations can achieve enhanced efficiency, higher quality products, customer satisfaction, and a competitive advantage.','reference':'American Society for Quality, “Continuous Improvement Model - Continual Improvement Tools | ASQ,” Asq.org, 2019. https://asq.org/quality-resources/continuous-improvement'},
  {'Id': 17, 'Term':"Deployment",'Description':'Software deployment involves releasing software applications to specific environments, involving key steps like packaging, testing, environment configuration, strategy, automation, production, monitoring, rollback, post-deployment activities, and security. It\'s crucial for the software development lifecycle, ensuring minimal disruption and optimal performance.','reference':'“Traditional Development/Integration/Staging/Production Practice for Software Development,” Disruptive Library Technology Jester, Dec. 04, 2006. https://dltj.org/article/software-development-practice/'},
  {'Id': 18, 'Term':"Source Control",'Description':'Source control is a software development system that tracks changes to files and folders, enabling collaboration, code management, conflict resolution, and backup. Common systems like Git, SVN, and Mercurial provide efficient collaboration, code management, and improved software quality.','reference':'F. Santacroce author., A. Olsson, R. Voss, and J. Narębski, Git : mastering version control. Packt Publishing, 2016. Accessed: Aug. 06, 2023. [Online]. Available: https://eds.p.ebscohost.com/eds/detail/detail?vid=0&sid=a00e23bc-ed8d-4b92-b41f-9ed87c505ee1%40redis&bdata=JnNpdGU9ZWRzLWxpdmUmc2NvcGU9c2l0ZQ%3d%3d#AN=deakin.b3649851&db=cat00097a'},
  {'Id': 19, 'Term':"Staging Environment",'Description':'A staging environment is a pre-production environment that closely replicates the production environment, allowing teams to test software, web applications, or changes before deploying them to the live or production environment. This approach ensures software stability, reliability, and reduces downtime risks','reference':'“Traditional Development/Integration/Staging/Production Practice for Software Development,” Disruptive Library Technology Jester, Dec. 04, 2006. https://dltj.org/article/software-development-practice/'},
  {'Id': 20, 'Term':"Deployment frequency",'Description':'Descriptionreplace','reference':'“Knovel,” app.knovel.com. https://app.knovel.com/hotlink/pdf/rcid:kpSMCCDO02/id:kt0130DYM3/successful-management/application-deployment?kpromoter=federation (accessed Aug. 06, 2023).'}

];

/* GET home page. */
router.get('/', function(req, res, next) {
  res.render('index', { title: 'SIT722 Devops Glossary', sub:'Welcome to mywebsite showing a collection of Devops terms and their brief description', names:nameList});
});

module.exports = router;
